name: frontend
description: A flutter frontend for the Shwokl app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.1
  equatable: ^1.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.0
  http: ^0.12.2
  material_design_icons_flutter: ^4.0.5345

dev_dependencies:
  build_runner: ">=1.6.2 <2.0.0"
  build_web_compilers: ">=2.12.0 <3.0.0"
  flutter_test:
    sdk: flutter
  lint: ^1.1.1

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - lib/src/assets/
    - lib/src/assets/pattern/