name: frontend
description: A flutter frontend for the Shwokl app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  auth:
    path: ./auth
  cupertino_icons: ^1.0.1
  equatable: ^1.2.5 # used for the BLoC pattern
  flushbar: ^1.10.4 # used for custom snackbars
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.0
  http: ^0.12.2 # used for sending api calls
  material_design_icons_flutter: ^4.0.5345 # used for extra icons
  url_launcher: ^5.1.4
  url_launcher_web: '>=0.1.0 <2.0.0'

dev_dependencies:
  build_runner: ">=1.6.2 <2.0.0"
  build_web_compilers: ">=2.12.0 <3.0.0"
  flutter_test:
    sdk: flutter
  lint: ^1.1.1

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/src/assets/fonts/Poppins/Thin.ttf
          weight: 100
        - asset: lib/src/assets/fonts/Poppins/ThinItalic.ttf
          weight: 100
          style: italic
        - asset: lib/src/assets/fonts/Poppins/ExtraLight.ttf
          weight: 200
        - asset: lib/src/assets/fonts/Poppins/ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: lib/src/assets/fonts/Poppins/Light.ttf
          weight: 300
        - asset: lib/src/assets/fonts/Poppins/LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/src/assets/fonts/Poppins/Regular.ttf
          weight: 400
        - asset: lib/src/assets/fonts/Poppins/Italic.ttf
          weight: 400
          style: italic
        - asset: lib/src/assets/fonts/Poppins/Medium.ttf
          weight: 500
        - asset: lib/src/assets/fonts/Poppins/MediumItalic.ttf
          weight: 500
          style: italic
        - asset: lib/src/assets/fonts/Poppins/SemiBold.ttf
          weight: 600
        - asset: lib/src/assets/fonts/Poppins/SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: lib/src/assets/fonts/Poppins/Bold.ttf
          weight: 700
        - asset: lib/src/assets/fonts/Poppins/BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/src/assets/fonts/Poppins/ExtraBold.ttf
          weight: 800
        - asset: lib/src/assets/fonts/Poppins/ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: lib/src/assets/fonts/Poppins/Black.ttf
          weight: 900
        - asset: lib/src/assets/fonts/Poppins/BlackItalic.ttf
          weight: 900
          style: italic

  assets:
    - lib/src/assets/
    - lib/src/assets/patterns/memphis-mini/